# Generated by Django 4.0.4 on 2022-05-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='details',
        ),
    ]
